import * as fs from 'fs';
import * as path from 'path';
import webpack from 'webpack';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import WebpackBar from 'webpackbar';

import { resolve, Env, EnvObject } from './env';
import getTsConfigPath from '../typescript/getConfigFile';
import { getVersion } from './version';
import { IUVPackConfig, IUVPackOptions } from '../const/config';
import logger from '../utils/logger';

export default (options: IUVPackOptions, config: IUVPackConfig) => {
    const common: any[] = [
        new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /^\.\/zh-cn$/),
        new webpack.BannerPlugin({
            banner: `Generated by iuv at ${new Date().toLocaleString()}`,
            entryOnly: true,
        }),
    ];

    if (config.ssr && config.ssr.enable === true) {
        // 添加Loadable Components插件
        try {
            const LoadablePlugin = require(resolve('node_modules', '@loadable', 'webpack-plugin'));
            common.push(new LoadablePlugin({
                filename: '../../server/ssr/loadable-stats.json',
            }));
        } catch (error) {}
    }

    // 当dllplugin生成的manifest文件存在时，添加dllplugin插件
    const manifestPath: string = Env.isProductuction ? 'env/manifest.json' : 'env/manifest.dev.json';
    if (fs.existsSync(path.resolve(options.clientPath!, manifestPath))) {
        common.push(
            new webpack.DllReferencePlugin({
                context: resolve(''),
                manifest: require(path.resolve(options.clientPath!, manifestPath)),
            })
        );
    }

    const production: any[] = [
            new MiniCssExtractPlugin({
                filename: config.disableUniqueOutput ? '[name].css' : `[name].${getVersion(config)}.css`,
                chunkFilename: config.disableUniqueOutput ? '[name].iuv.css' : '[name].[chunkhash:4].css',
                ignoreOrder: true,
            }),
        ],
        development: any[] = [
            new MiniCssExtractPlugin({
                filename: '[name].css',
                chunkFilename: '[name].iuv.css',
                ignoreOrder: true,
            }),
            new ForkTsCheckerWebpackPlugin({
                async: true,
                typescript: {
                    enabled: true,
                    context: resolve(''),
                    configFile: getTsConfigPath(resolve('')),
                    mode: 'write-tsbuildinfo',
                    memoryLimit: 3000,
                    configOverwrite: {
                        // 不检查server端类型
                        exclude: [options.serverSourcePath || 'node_modules'],
                    },
                },
                logger: {
                    issues: {
                        info: (m) => logger.log('[类型检查]', m),
                        log: (m) => logger.log('[类型检查]', m),
                        error: (m) => logger.log('[类型检查]', m),
                    },
                },
            }),
            new WebpackBar({
                name: '[iuv] client',
                basic: false,
            }),
        ];

    const configObject: EnvObject<any[]> = {
        common,
        production,
        development,
    };

    // 合并用户配置
    if (Array.isArray(config.webpackPlugins)) {
        configObject.common = config.webpackPlugins;
        configObject.production = [];
        configObject.development = [];
    } else if (typeof config.webpackPlugins === 'function') {
        configObject.common = config.webpackPlugins(common.concat(configObject[Env.env]));
        configObject.production = [];
        configObject.development = [];
    }

    return configObject;
};
